/*
This SQL script initializes the database schema for the application. It performs the following tasks:
1. Drops the existing 'admin' user and all objects owned by it.
2. Creates a new 'admin' user with superuser privileges and sets an encrypted password.
3. Grants all privileges on the 'postgres' database to the 'admin' user.
4. Grants all privileges on all tables and sequences in the 'public' schema to the 'admin' user.
5. Creates the 'users' table with columns for user information and a UUID primary key.
6. Creates the 'hobbies' table with columns for hobby information and an auto-incrementing integer primary key.
7. Creates the 'user_hobbies' table to establish a many-to-many relationship between users and hobbies.
8. Creates the 'user_friends' table to establish a many-to-many relationship between users and their friends.
9. Creates the 'groups' table with columns for group information and an auto-incrementing integer primary key.
10. Creates the 'group_members' table to establish a many-to-many relationship between groups and their members.
*/
-- DB init code - runs every time the app starts up

drop owned by admin;
drop user admin;

create user admin superuser encrypted password 'adminPassword';
grant all privileges on database postgres to admin;

grant all privileges on all tables in schema public to admin;
grant all privileges on all sequences in schema public to admin;

create table if not exists users (
    id uuid DEFAULT gen_random_uuid(),
    email text unique,
    "password" text,
    first_name text,
    last_name text,
    lower_budget integer,
    upper_budget integer,
    primary key (id)
);

create table if not exists hobbies (
    id integer generated by default as identity,
    "name" text,
    min_age integer,
    min_participants integer,
    max_participants integer,
    primary key (id)
);

create table if not exists user_hobbies (
    id integer generated by default as identity,
    "user" uuid,
    hobby integer,
    primary key (id),
    foreign key ("user") references users,
    foreign key (hobby) references hobbies
);

create table if not exists user_friends (
    id integer generated by default as identity,
    "user" uuid,
    friend uuid,
    primary key (id),
    foreign key ("user") references users,
    foreign key (friend) references users
);

-- create table if not exists groups (
--     id integer generated by default as identity,
--     conversation int,
--     "name" text,
--     description text,
--     primary key (id),
--     foreign key (conversation) references conversations
-- );

-- create table if not exists group_members (
--     id integer generated by default as identity,
--     "user" uuid,
--     "group" integer,
--     primary key (id),
--     foreign key ("user") references users,
--     foreign key ("group") references groups
-- );

-- add a default user
insert into users (email, "password", first_name, last_name, lower_budget, upper_budget) values ('admin@localhost', 'adminPassword', 'admin', 'admin', 0, 1000);
insert into users (email, "password", first_name, last_name, lower_budget, upper_budget) values ('user@localhost', 'userPassword', 'user', 'user', 0, 1000);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('hiking', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('swimming', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('running', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('biking', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('reading', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('writing', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('cooking', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('baking', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('dancing', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('singing', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('playing music', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('playing video games', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('playing board games', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('playing card games', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('playing sports', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('watching movies', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('watching tv', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('watching anime', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('watching sports', 0, 1, 10);
insert into hobbies ("name", min_age, min_participants, max_participants) values ('watching youtube', 0, 1, 10);